name: github pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          version: 'latest'
          runtime: 'node@lts'
      - run: pnpm build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
